export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100
};

export const DASHBOARD = {
  RECENT_ACTIVITY_DEFAULT_LIMIT: 5,
  RECENT_ACTIVITY_MAX_LIMIT: 20,
  TRENDS_MONTH_LIMIT: 12
};

export const AUTH = {
  REFRESH_TOKEN_BYTES: 40
};
